### ISSUE TITLE
com.eddysystems.eddy.EddyFileListener.updateIntentions doesn't commit document before intentions hint is shown

### ISSUE THREAD

**Issue by akozlova** [eddysystems/eddy#41]
Resulted exception:
<< Element: class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl because: parent is null
invalidated at: see attachment

com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl because: parent is null
invalidated at: see attachment
    at com.intellij.psi.impl.source.tree.CompositePsiElement.getProject(CompositePsiElement.java:295)
    at com.intellij.refactoring.util.RefactoringUtil.getTypeByExpression(RefactoringUtil.java:403)
    at com.intellij.codeInsight.daemon.impl.quickfix.ChangeMethodSignatureFromUsageFix.findNewParamsPlace(ChangeMethodSignatureFromUsageFix.java:407)
    at com.intellij.codeInsight.daemon.impl.quickfix.ChangeMethodSignatureFromUsageFix.getNewParametersInfo(ChangeMethodSignatureFromUsageFix.java:319)
    at com.intellij.codeInsight.daemon.impl.quickfix.ChangeMethodSignatureFromUsageFix.getShortText(ChangeMethodSignatureFromUsageFix.java:102)
    at com.intellij.codeInsight.daemon.impl.quickfix.ChangeMethodSignatureFromUsageFix.getText(ChangeMethodSignatureFromUsageFix.java:88)
    at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching.<init>(IntentionActionWithTextCaching.java:55)
    at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching.<init>(IntentionActionWithTextCaching.java:50)
    at com.intellij.codeInsight.intention.impl.IntentionListStep.wrapAction(IntentionListStep.java:185)
    at com.intellij.codeInsight.intention.impl.IntentionListStep.wrapActionsTo(IntentionListStep.java:164)
    at com.intellij.codeInsight.intention.impl.IntentionListStep.wrapAndUpdateActions(IntentionListStep.java:106)
    at com.intellij.codeInsight.intention.impl.IntentionListStep.<init>(IntentionListStep.java:90)
    at com.intellij.codeInsight.intention.impl.IntentionHintComponent.<init>(IntentionHintComponent.java:392)
    at com.intellij.codeInsight.intention.impl.IntentionHintComponent.showIntentionHint(IntentionHintComponent.java:157)
    at com.intellij.codeInsight.intention.impl.IntentionHintComponent.showIntentionHint(IntentionHintComponent.java:146)
    at com.eddysystems.eddy.EddyFileListener$3.run(EddyFileListener.java:181)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:647)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

invalidation trace:
java.lang.Throwable
    at com.intellij.psi.impl.DebugUtil.startPsiModification(DebugUtil.java:530)
    at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:146)
    at com.intellij.psi.impl.DocumentCommitProcessor$2.run(DocumentCommitProcessor.java:217)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$8.compute(CodeStyleManagerImpl.java:682)
    at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:124)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$10.compute(CodeStyleManagerImpl.java:717)
    at com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:919)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:713)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:679)
    at com.intellij.psi.impl.DocumentCommitProcessor.doActualPsiChange(DocumentCommitProcessor.java:202)
    at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:138)
    at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:128)
    at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:321)
    at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:137)
    at com.intellij.psi.impl.PsiDocumentManagerBase$3.run(PsiDocumentManagerBase.java:292)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1005)
    at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:289)
    at com.intellij.psi.impl.DocumentCommitThread$5.run(DocumentCommitThread.java:522)
    at com.intellij.psi.impl.DocumentCommitThread.commitSynchronously(DocumentCommitThread.java:418)
    at com.intellij.psi.impl.PsiDocumentManagerBase$5.run(PsiDocumentManagerBase.java:375)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1005)
    at com.intellij.psi.impl.PsiDocumentManagerBase.b(PsiDocumentManagerBase.java:367)
    at com.intellij.psi.impl.PsiDocumentManagerBase.commitDocument(PsiDocumentManagerBase.java:278)
    at com.intellij.psi.impl.PsiDocumentManagerBase.commitAllDocuments(PsiDocumentManagerBase.java:212)
    at com.intellij.codeInsight.TargetElementUtil.findReference(TargetElementUtil.java:120)
    at com.intellij.codeInsight.TargetElementUtil.findReference(TargetElementUtil.java:101)
    at com.intellij.codeInspection.actions.UnimplementInterfaceAction.isAvailable(UnimplementInterfaceAction.java:54)
    at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:132)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:113)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:297)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:294)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:294)
    at com.eddysystems.eddy.EddyFileListener$3.run(EddyFileListener.java:177)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:647)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by martinwicke** [comment]
I hope https://github.com/eddysystems/eddy/commit/bd9a25343d0b8a970cb24cf52d7226838487b8a5 fixes this. Could not immediately reproduce. If you have a good way to test for it, I'd appreciate that.

**Comment by akozlova** [comment]
I disagree: when you do Application.invokeLater, before your runnable is invoked the world could be changed completely (e.g. by another postponed runnable). So the only way I see: you need to PsiDocumentManager.commitAllDocuments at the first line of runnable. BTW You need to check that the project was not disposed, but this is a good idea anyway.

**Comment by martinwicke** [comment]
Ah. Thanks. I'll fix that. Is it worth keeping the performForCommittedDocument to make it less likely that the commit runs in the dispatch thread?

**Comment by akozlova** [comment]
No, invokeLater eliminates all checks you do before it. Just commitAllDocuments. 

BTW you may use project.getDisposed() to ensure that your runnable won't be invoked after project dispose

**Comment by martinwicke** [comment]
I've been using getDisposed in the condition for invokeLater, I hope that works.
